CREATE TABLE ERROR_LOG
    (ID INT PRIMARY KEY, 
    USER_CREATED_BY TEXT NOT NULL,
    DATE_CREATED DATETIME NOT NULL,
    EXCEPTION_THROWN TEXT NOT NULL,
    STACKTRACE TEXT,
    ERROR_MSG TEXT NOT NULL, 
    SEVERITY INT, 
    SOURCE TEXT);

    